cleanForLocomotif:
	rm -rf Misc RNApackage Tests
	rm -f alifold.hh
	rm -f ali_macrostate.gap
	rm -f ali_microstate.gap
	rm -f ali_nodangle.gap
	rm -f ali_overdangle.gap
	rm -f eval_nodangle.gap
	rm -f macrostate.gap
	rm -f macrostateCenter.gap
	rm -f mfesubopt.hh
	rm -f microstate.gap
	rm -f nodangle.gap
	rm -f overdangle.gap
	rm -f pfunc_answer_macrostate.hh
	rm -f pfunc_filter_foldrna.hh
	rm -f pfunc_filter_macrostate.hh
	rm -f README.txt
	rm -f sampling_wrapper.pl
	rm -f structure2shape.gap
	rm -f Algebras/alg_ali_consensus.gap
	rm -f Algebras/alg_ali_dotBracket.gap
	rm -f Algebras/alg_ali_hishapes.gap
	rm -f Algebras/alg_ali_mfe.gap
	rm -f Algebras/alg_ali_mfe_macrostate.gap
	rm -f Algebras/alg_ali_mis.gap
	rm -f Algebras/alg_ali_shapes.gap
	rm -f Algebras/alg_basepairMax.gap
	rm -f Algebras/alg_centers.gap
	rm -f Algebras/alg_dotBracket.gap
	rm -f Algebras/alg_eval_dotBracket.gap
	rm -f Algebras/alg_eval_mfe.gap
	rm -f Algebras/alg_hishapes.gap
	rm -f Algebras/alg_mfe.gap
	rm -f Algebras/alg_mfe_macrostate.gap
	rm -f Algebras/alg_pfunc.gap
	rm -f Algebras/alg_pfunc_macrostate.gap
	rm -f Algebras/alg_shapes.gap
	rm -f Algebras/alg_shapes_rope.gap
	rm -f Grammars/gra_eval_nodangle.gap
	rm -f Grammars/gra_locomotif_overdangle.gap
	rm -f Grammars/gra_macrostate.gap
	rm -f Grammars/gra_macrostate_centers.gap
	rm -f Grammars/gra_microstate.gap
	rm -f Grammars/gra_nodangle.gap
	rm -f Grammars/gra_overdangle.gap
	rm -f Signatures/sig_eval_foldrna.gap
	rm -f Signatures/sig_foldrna.gap
