name: github action build & CI

on:
  push:
    branches: [ python ]
  pull_request:
    branches: [ python ]

jobs:
  backprop:
    runs-on: ubuntu-latest
    steps:
    # install gapcs
    - name: update apt
      run: sudo apt-get update
    - name: Install dependencies
      run: sudo apt-get install flex bison make libboost-all-dev libgsl-dev python3 python3-pip python3-biopython swig
    - name: clone gapc
      run: git clone -b swig_rna https://github.com/jlab/gapc.git $GITHUB_WORKSPACE/../gapc
    - name: configure
      run: cd $GITHUB_WORKSPACE/../gapc && ./configure
    - name: make
      run: |
        cd $GITHUB_WORKSPACE/../gapc && make -j 2
        cd $GITHUB_WORKSPACE/../gapc && make librna/rnalib.py
    - name: make install
      run: cd $GITHUB_WORKSPACE/../gapc && sudo make install

    - uses: actions/checkout@v2
    - name: configure fold-grammars
      run: |
        cd $GITHUB_WORKSPACE/../fold-grammars
        sed -i "s#bgapDir = '/vol/gapc/'#bgapDir = '/usr/local/'#" Misc/Applications/lib/foldGrammars/Settings.pm
        sed -i "s#rootDir = '/vol/fold-grammars/src/'#rootDir = '`pwd`/'#" Misc/Applications/lib/foldGrammars/Settings.pm
    - name: execute tests
      run: |
        cd $GITHUB_WORKSPACE/../fold-grammars
        cd Misc/Test-Suite/PythonStyle/
        make backprop
        ls -la
